### ISSUE TITLE
Change workflow from Daily to Immediately

### ISSUE THREAD

**Issue by calldelegation** [FuelLabs/breaking-change-log#14]
Workflow should trigger from fuels-ts, rust-ts and sway with the following to send `migrations-and-disclosures` to kick off a run

```
name: Trigger Dispatch on Release

on:
  release:
    types: [published]

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest

    steps:
    - name: Send Repository Dispatch
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/<your-repo-owner>/<your-repo-name>/dispatches \
          -d '{"event_type":"update_versions"}'
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
```
